version: "3.1"

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            # - ${DB_PORT}:${DB_PORT}
            - 5434:${DB_PORT}
  
    http_api:
        build: 
            context: .
            # dockerfile: Dockerfile-server-golang-http
        restart: always
        ports:
            - ${DEV_HTTP_SERVER_PORT}:${DEV_HTTP_SERVER_PORT}
        depends_on:
            - postgres